apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
spec:
  replicas: 1
  bootstrapServers: http://192.168.1.47:30985
  authentication:
    type: scram-sha-512
    username: admin
    passwordSecret:
      secretName: admin
      password: password
  http:
    port: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: my-bridge-nodeport
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30083
  selector:
    strimzi.io/cluster: my-bridge
    

