apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: display-line-balance-producer-topic
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 1
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: display-line-balance-consumer-topic
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 1
  replicas: 1

