apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: display-line-balance-producer-topic
          patternType: literal
        operations:
          - Describe
          - Read
          - Create
          - Write
        host: "*"
      - resource:
          type: topic
          name: display-line-balance-consumer-topic
          patternType: literal
        operations:
          - Describe
          - Read
          - Create
          - Write
        host: "*"

